#!/bin/bash

# Script to help organize commits for the Voting dApp project
# This script shows suggested commit groups

echo "=== Suggested Commit Groups ==="
echo ""
echo "1. Configuration & Tooling:"
echo "   - Add Prettier configuration"
echo "   - Add ESLint ignore file"
echo "   - Add EditorConfig"
echo "   - Update package.json with scripts"
echo ""
echo "2. Testing Infrastructure:"
echo "   - Add Jest configuration"
echo "   - Add Jest setup file"
echo "   - Add test dependencies to package.json"
echo ""
echo "3. Documentation:"
echo "   - Add comprehensive README"
echo "   - Add CONTRIBUTING guide"
echo "   - Add GitHub issue templates"
echo "   - Add PR template"
echo ""
echo "4. CI/CD:"
echo "   - Add GitHub Actions workflow"
echo "   - Add coverage configuration"
echo ""
echo "5. Frontend Tests:"
echo "   - Add utility function tests"
echo "   - Add custom hook tests"
echo "   - Add component tests"
echo ""
echo "6. Security & Performance:"
echo "   - Add security headers to Next.js config"
echo "   - Add PWA manifest"
echo "   - Update layout metadata"
echo ""
echo "7. Docker & Deployment:"
echo "   - Add Dockerfile"
echo "   - Add docker-compose.yml"
echo "   - Add .dockerignore"
echo ""
echo "=== Ready to commit! ==="

